### ISSUE TITLE
Create Student Class

### ISSUE THREAD

**Issue by iFialAtFail** [Ferris-DMSE/TeamPlatinumViewer#3]
Create Student class according to spec

**Comment by iFialAtFail** [comment]
Still needs work, converting to C# properties, and remove redundancies in naming scheme.
Instead of the fields being "StudentName", consider just "Name" as the "Student" part is taken care of in the class level. For instance:
Student newStudent = Student();
newStudent.StudentName = "Fred"; //Adding the Student before name makes for longer lines and redundancy.

**Comment by JakJon** [comment]
Finished creation of student class.
